"""Versioned prompt names for phase-12 agents."""

TRIAGE_PROMPT = "agent_triage"
TRIAGE_VERSION = "v1"
MAINTAINER_PROMPT = "agent_maintainer"
MAINTAINER_VERSION = "v1"
HEALER_PROMPT = "agent_healer"
HEALER_VERSION = "v1"
GENERATOR_PROMPT = "agent_generator"
GENERATOR_VERSION = "v1"
UNIT_GEN_PROMPT = "agent_unit_gen"
UNIT_GEN_VERSION = "v1"
