"""Generate typed locator accessors from locators.yaml.

Usage:
    python -m questline.drivers.codegen path/to/locators.yaml -o path/to/generated.py

The output file is meant to be committed. Do not hand-edit it — regenerate instead.
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path

from questline.drivers.locators import Locator, LocatorRegistry, load_locators

_GENERATED_HEADER = '''\
# AUTO-GENERATED by questline.drivers.codegen - DO NOT EDIT BY HAND.
# Source: {source}
# Regenerate: python -m questline.drivers.codegen {source} -o {output}

from __future__ import annotations

from questline.drivers.locators import Locator, LocatorStrategy

'''


def _ident(name: str) -> str:
    """Turn a locator/page name into a valid Python identifier."""
    cleaned = re.sub(r"[^0-9a-zA-Z_]", "_", name)
    if not cleaned:
        cleaned = "unnamed"
    if cleaned[0].isdigit():
        cleaned = f"_{cleaned}"
    return cleaned


def _locator_literal(loc: Locator) -> str:
    scope = "None" if loc.scope is None else repr(loc.scope)
    return (
        f"Locator(by=LocatorStrategy.{loc.by.name}, value={loc.value!r}, scope={scope})"
    )


def generate_module(registry: LocatorRegistry, *, source: str, output: str) -> str:
    """Return Python source for typed page accessor classes."""
    source_disp = Path(source).as_posix()
    output_disp = Path(output).as_posix()
    lines = [_GENERATED_HEADER.format(source=source_disp, output=output_disp)]
    for page in registry.pages():
        class_name = _ident(page)
        lines.append(f"class {class_name}:")
        locs = registry.locators_for(page)
        if not locs:
            lines.append("    pass")
        else:
            for name, loc in sorted(locs.items()):
                attr = _ident(name)
                lines.append(f"    {attr} = {_locator_literal(loc)}")
        lines.append("")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def write_generated(registry: LocatorRegistry, output: Path, *, source: str) -> None:
    text = generate_module(registry, source=source, output=str(output))
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(text, encoding="utf-8")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate typed locators from locators.yaml")
    parser.add_argument("yaml_path", type=Path, help="Path to locators.yaml")
    parser.add_argument(
        "-o",
        "--output",
        type=Path,
        required=True,
        help="Output .py path (committed; do not hand-edit)",
    )
    args = parser.parse_args(argv)
    registry = load_locators(args.yaml_path)
    write_generated(registry, args.output, source=str(args.yaml_path))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
