# AUTO-GENERATED by questline.drivers.codegen — DO NOT EDIT BY HAND.
# Source: examples/unity-smoke/locators.yaml

from __future__ import annotations

from questline.drivers.locators import Locator, LocatorStrategy


class Smoke:
    root = Locator(by=LocatorStrategy.NAME, value="QuestlineSmokeRoot")
    button = Locator(by=LocatorStrategy.NAME, value="QuestlineSmokeButton")
