# AUTO-GENERATED by questline.drivers.codegen - DO NOT EDIT BY HAND.
# Source: examples/locators.yaml
# Regenerate: python -m questline.drivers.codegen examples/locators.yaml -o examples/generated_locators.py

from __future__ import annotations

from questline.drivers.locators import Locator, LocatorStrategy


class Hud:
    coins_label = Locator(by=LocatorStrategy.TEXT, value='Coins: 0', scope=None)
    play_button = Locator(by=LocatorStrategy.COMPONENT, value='UnityEngine.UI.Button', scope=None)


class Shop:
    open_button = Locator(by=LocatorStrategy.ID, value='shop.open', scope=None)
    root = Locator(by=LocatorStrategy.NAME, value='ShopPanel', scope='Canvas')
