# AUTO-GENERATED by questline.drivers.codegen - DO NOT EDIT BY HAND.
# Source: examples/locators.yaml
# Regenerate: python -m questline.drivers.codegen examples/locators.yaml -o examples/generated_locators.py

from __future__ import annotations

from questline.drivers.locators import Locator, LocatorStrategy


class Hud:
    coins_label = Locator(by=LocatorStrategy.ID, value='hud.coins', scope=None)
    root = Locator(by=LocatorStrategy.ID, value='hud.root', scope=None)
    shop_button = Locator(by=LocatorStrategy.ID, value='hud.shop', scope=None)


class MainMenu:
    play_button = Locator(by=LocatorStrategy.ID, value='main.play', scope=None)
    root = Locator(by=LocatorStrategy.ID, value='main.root', scope=None)


class Popup:
    dismiss = Locator(by=LocatorStrategy.ID, value='popup.dismiss', scope=None)
    rate_us = Locator(by=LocatorStrategy.ID, value='popup.rate_us', scope=None)


class Shop:
    buy_pack_button = Locator(by=LocatorStrategy.ID, value='shop.buy_pack', scope=None)
    close_button = Locator(by=LocatorStrategy.ID, value='shop.close', scope=None)
    open_button = Locator(by=LocatorStrategy.ID, value='hud.shop', scope=None)
    root = Locator(by=LocatorStrategy.ID, value='shop.root', scope=None)
